apiVersion: v1
kind: ConfigMap
metadata:
  name: super-organizer-config
  namespace: super-organizer
data:
  application.yml: |
    server:
      port: 8080
    
    spring:
      application:
        name: Super Organizer
      datasource:
        url: jdbc:postgresql://super-organizer-postgres:5432/super_organizer_db
        driver-class-name: org.postgresql.Driver
        username: postgres
        password: password
      jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
          ddl-auto: update
        show-sql: false
        properties:
          hibernate:
            format_sql: true
    
    springdoc:
      api-docs:
        path: /api-docs
      swagger-ui:
        path: /swagger-ui.html
      info:
        title: Super Organizer API
        description: A powerful task management REST API
        version: 1.0.0