apiVersion: v1
kind: PersistentVolume
metadata:
  name: super-organizer-postgres-pv
  namespace: super-organizer
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/postgres"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: super-organizer-postgres-pvc
  namespace: super-organizer
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi