apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
  namespace: super-organizer
data:
  1-schema.sql: |
    -- Create tasks table
    CREATE TABLE IF NOT EXISTS tasks (
        id BIGSERIAL PRIMARY KEY,
        date DATE NOT NULL,
        task_name VARCHAR(255) NOT NULL,
        comment TEXT,
        deadline TIMESTAMP,
        priority VARCHAR(10) NOT NULL CHECK (priority IN ('HIGH', 'MEDIUM', 'LOW')),
        task_type VARCHAR(10) NOT NULL CHECK (task_type IN ('WORK', 'HOME')),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    
    -- Create index for better performance
    CREATE INDEX IF NOT EXISTS idx_tasks_date ON tasks(date);
    CREATE INDEX IF NOT EXISTS idx_tasks_priority ON tasks(priority);
    CREATE INDEX IF NOT EXISTS idx_tasks_type ON tasks(task_type);
    CREATE INDEX IF NOT EXISTS idx_tasks_deadline ON tasks(deadline);
  
  2-sample-data.sql: |
    -- Insert sample tasks
    INSERT INTO tasks (date, task_name, comment, deadline, priority, task_type) VALUES
    ('2024-01-15', 'Complete project report', 'Quarterly project summary', '2024-01-20 17:00:00', 'HIGH', 'WORK'),
    ('2024-01-16', 'Team meeting', 'Weekly standup', '2024-01-16 10:00:00', 'MEDIUM', 'WORK'),
    ('2024-01-17', 'Grocery shopping', 'Buy groceries for the week', '2024-01-18 18:00:00', 'LOW', 'HOME'),
    ('2024-01-18', 'Code review', 'Review pull requests', '2024-01-19 16:00:00', 'HIGH', 'WORK'),
    ('2024-01-19', 'Laundry', 'Wash clothes', NULL, 'MEDIUM', 'HOME'),
    ('2024-01-20', 'Client presentation', 'Present quarterly results', '2024-01-20 14:00:00', 'HIGH', 'WORK'),
    ('2024-01-21', 'Exercise', 'Go to the gym', '2024-01-21 19:00:00', 'MEDIUM', 'HOME'),
    ('2024-01-22', 'Database optimization', 'Optimize database queries', '2024-01-25 17:00:00', 'HIGH', 'WORK'),
    ('2024-01-23', 'Dinner with friends', 'Meet at restaurant', '2024-01-23 20:00:00', 'LOW', 'HOME'),
    ('2024-01-24', 'Security audit', 'Conduct security review', '2024-01-26 15:00:00', 'HIGH', 'WORK');