apiVersion: v1
kind: Secret
metadata:
  name: super-organizer-secret
  namespace: super-organizer
type: Opaque
data:
  # Base64 encoded values: echo -n "rcherepin" | base64
  postgres-username: cmNoZXJlcGlu
  # Base64 encoded values: echo -n "Wrongpass911#" | base64
  postgres-password: V3JvbmdwYXNzOTExIw==
  # Base64 encoded values: echo -n "rcherepin_db" | base64
  postgres-database: cmNoZXJlcGluX2Ri